apiVersion: v1
kind: Service
metadata:
  name: rsyslog-server-service
  labels:
    app: rsyslog-server
spec:
  type: LoadBalancer
  ports:
  - name: tcp
    port: 514
    protocol: TCP
  selector:
    app: rsyslog-server
